[package]
name = "protogen"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
description = """Protocol description language & parser generator"""
license = "MIT/Apache-2.0"
homepage = "https://github.com/mwylde/protogen"
