[package]
name = "protogen-compiler"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]

[dependencies]
regex = "^1"
lazy_static = "^1.2"

[dependencies.nom]
version = "^4.1"
features = ["verbose-errors"]
