[package]
name = "protogen-compiler"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
edition = "2018"

[dependencies]
regex = "^1"
lazy_static = "^1.2"
lalrpop-util = "0.19.0"

[build-dependencies]
lalrpop = {version = "0.19.0", features = ["lexer"]}
